version: '2'
services:
  elasticsearch:
    hostname: elastic
    domainname: elk-local
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - "9200"
      - "9300"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - data:/data
  kibana:
    hostname: kibana
    domainname: elk-local
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
      - "80:5601"
  logstash:
    hostname: logstash
    domainname: elk-local
    command: logstash -e 'input { stdin {  } http { port => 8080 } } output { elasticsearch { hosts => [ 'elasticsearch' ] index => "elk-data-%{+YYYY.MM.dd}" } stdout { } }'
    image: docker.elastic.co/logstash/logstash:6.4.0
    ports:
      - "8080:8080"
volumes:
  data:
    driver: local
